# Generated by Django 5.1.2 on 2025-02-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_purchaseorder_status_purchaseorder_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='order_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='payment_status',
            field=models.CharField(choices=[('U', 'Unpaid'), ('P', 'Paid'), ('R', 'Refunded')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
