# Generated by Django 5.1.2 on 2025-01-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_userprofile_user_delete_passwordresetcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_dawa', models.CharField(max_length=255)),
                ('jina_mnunuzi', models.CharField(max_length=255)),
                ('namba_simu', models.CharField(max_length=15)),
                ('maelezo_ziada', models.TextField(blank=True, null=True)),
                ('tarehe_ya_oda', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
