# Generated by Django 5.1.2 on 2024-12-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
