# Generated by Django 5.1.2 on 2025-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_saleorder_order_notes_saleorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], default='U', max_length=100),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='P', max_length=100),
        ),
    ]
