# Generated by Django 5.1.2 on 2024-12-25 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_passwordresetcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='request_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='uidb64',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
