# Generated by Django 5.1.2 on 2025-02-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dawa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaoniMteja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_mteja', models.CharField(max_length=100)),
                ('eneo', models.CharField(max_length=100)),
                ('ujumbe', models.TextField()),
                ('tarehe_iliyoandikwa', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
