# Generated by Django 5.1.2 on 2025-02-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_saleorder_created_by_alter_saleorder_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='order_notes',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='shipping_address',
        ),
    ]
