# Generated by Django 5.1.2 on 2025-01-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresetcode_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
