# Generated by Django 5.1.2 on 2025-02-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
