# Generated by Django 5.1.2 on 2025-03-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_cashbook_alter_saleorder_payment_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashBook',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default='Cash', help_text='Select the payment method (Cash or Bank).', max_length=10),
        ),
    ]
