# Generated by Django 5.1.2 on 2025-03-09 20:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_supplier_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[users.models.validate_contact_number]),
        ),
    ]
